### ISSUE TITLE
Whenever I install rgthree reroute nodes I get this frustrating error

### ISSUE THREAD

**Issue by Ferniclestix** [rgthree/rgthree-comfy#19]
This error kills my workflow, deletes groups and throws nodes all over the place and it is very frustrating, any time use these nodes in a node graph and then delete them out. it will throw errors if I try to load the workflow from an image or json.

![image](https://github.com/rgthree/rgthree-comfy/assets/128430314/7a16685a-8548-494d-a8ec-85661487592b)

**Comment by Ferniclestix** [comment]
And yeah, it doenst look like it comes from rgthree, I know, but the bug only happens when I install it. :<

**Comment by rgthree** [comment]
I know it doesn't mention the rgthree nodes, but can you send me your workflow, or an example of one that breaks. I think there's a bug (that's fixed in dev branch, but wondering if I can patch workflows that may be broken)

**Comment by Ferniclestix** [comment]
https://drive.google.com/file/d/1Cge5-S9u65waLVGjHoS23XCFQFGaKEFX/view?usp=sharing

**Comment by rgthree** [comment]
Thank you! If you pull the latest and load your workflow, a little message should appear on top with the ability to fix the corrupt linking data.

Let me know if that works for you. I used your uploaded workflow to test it.

**Comment by Ferniclestix** [comment]
Ill have a look at this tomorrow, thx

**Comment by Ferniclestix** [comment]
two weeks later, nope still get that error and im fully updated.
